export default {
  REQUEST_TYPES: {
    POST: 'POST',
    GET: 'GET',
    DELETE: 'DELETE',
    PUT: 'PUT',
    PATCH: 'PATCH',
    UPLOAD: 'UPLOAD',
    HEAD: 'HEAD',
  },
  RESPONSE_STATUS: {
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,
    UNAUTHORIZED: 401,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500,
    UNREACHABLE: 503,
  },
  IMAGE_GRID_PROPS: {
    MAX_IMAGE_COUNT_ON_GRID: 5
  }
};

